//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int idCurso { get; set; }
        public int idAluno { get; set; }
        public int idMateria { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<System.DateTime> dataAtualizacao { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
